// Fake API service for managing all candidates
export const manageCandidateApi = {
  // Get all candidates from all job postings
  getAllCandidates: async () => {
    // Simulate API delay
    await new Promise((resolve) => setTimeout(resolve, 1000))

    // Fake data with jobPostingName
    return [
      {
        id: 1,
        name: "John Doe",
        email: "john.doe@email.com",
        phone: "+1234567890",
        status: "In-Review",
        score: 85,
        createdAt: "2024-01-15T10:30:00Z",
        resumeFile: "https://example.com/resume1.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 2,
        name: "Jane Smith",
        email: "jane.smith@email.com",
        phone: "+1234567891",
        status: "Interview",
        score: 92,
        createdAt: "2024-01-14T14:20:00Z",
        resumeFile: "https://example.com/resume2.pdf",
        jobPostingName: "Backend Engineer",
        jobPostingId: "job-2",
      },
      {
        id: 3,
        name: "Mike Johnson",
        email: "mike.johnson@email.com",
        phone: "+1234567892",
        status: "Hired",
        score: 88,
        createdAt: "2024-01-13T09:15:00Z",
        resumeFile: "https://example.com/resume3.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 4,
        name: "Sarah Wilson",
        email: "sarah.wilson@email.com",
        phone: "+1234567893",
        status: "Rejected",
        score: 65,
        createdAt: "2024-01-12T16:45:00Z",
        resumeFile: null,
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 5,
        name: "David Brown",
        email: "david.brown@email.com",
        phone: "+1234567894",
        status: "In-Review",
        score: 78,
        createdAt: "2024-01-11T11:30:00Z",
        resumeFile: "https://example.com/resume5.pdf",
        jobPostingName: "Backend Engineer",
        jobPostingId: "job-2",
      },
      {
        id: 6,
        name: "Lisa Garcia",
        email: "lisa.garcia@email.com",
        phone: "+1234567895",
        status: "Interview",
        score: 91,
        createdAt: "2024-01-10T13:20:00Z",
        resumeFile: "https://example.com/resume6.pdf",
        jobPostingName: "Full Stack Developer",
        jobPostingId: "job-4",
      },
      {
        id: 7,
        name: "Tom Anderson",
        email: "tom.anderson@email.com",
        phone: "+1234567896",
        status: "In-Review",
        score: 82,
        createdAt: "2024-01-09T08:45:00Z",
        resumeFile: "https://example.com/resume7.pdf",
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 8,
        name: "Emma Davis",
        email: "emma.davis@email.com",
        phone: "+1234567897",
        status: "Hired",
        score: 95,
        createdAt: "2024-01-08T15:10:00Z",
        resumeFile: "https://example.com/resume8.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 3,
        name: "Mike Johnson",
        email: "mike.johnson@email.com",
        phone: "+1234567892",
        status: "Hired",
        score: 88,
        createdAt: "2024-01-13T09:15:00Z",
        resumeFile: "https://example.com/resume3.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 4,
        name: "Sarah Wilson",
        email: "sarah.wilson@email.com",
        phone: "+1234567893",
        status: "Rejected",
        score: 65,
        createdAt: "2024-01-12T16:45:00Z",
        resumeFile: null,
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 5,
        name: "David Brown",
        email: "david.brown@email.com",
        phone: "+1234567894",
        status: "In-Review",
        score: 78,
        createdAt: "2024-01-11T11:30:00Z",
        resumeFile: "https://example.com/resume5.pdf",
        jobPostingName: "Backend Engineer",
        jobPostingId: "job-2",
      },
      {
        id: 6,
        name: "Lisa Garcia",
        email: "lisa.garcia@email.com",
        phone: "+1234567895",
        status: "Interview",
        score: 91,
        createdAt: "2024-01-10T13:20:00Z",
        resumeFile: "https://example.com/resume6.pdf",
        jobPostingName: "Full Stack Developer",
        jobPostingId: "job-4",
      },
      {
        id: 7,
        name: "Tom Anderson",
        email: "tom.anderson@email.com",
        phone: "+1234567896",
        status: "In-Review",
        score: 82,
        createdAt: "2024-01-09T08:45:00Z",
        resumeFile: "https://example.com/resume7.pdf",
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 8,
        name: "Emma Davis",
        email: "emma.davis@email.com",
        phone: "+1234567897",
        status: "Hired",
        score: 95,
        createdAt: "2024-01-08T15:10:00Z",
        resumeFile: "https://example.com/resume8.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 3,
        name: "Mike Johnson",
        email: "mike.johnson@email.com",
        phone: "+1234567892",
        status: "Hired",
        score: 88,
        createdAt: "2024-01-13T09:15:00Z",
        resumeFile: "https://example.com/resume3.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 4,
        name: "Sarah Wilson",
        email: "sarah.wilson@email.com",
        phone: "+1234567893",
        status: "Rejected",
        score: 65,
        createdAt: "2024-01-12T16:45:00Z",
        resumeFile: null,
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 5,
        name: "David Brown",
        email: "david.brown@email.com",
        phone: "+1234567894",
        status: "In-Review",
        score: 78,
        createdAt: "2024-01-11T11:30:00Z",
        resumeFile: "https://example.com/resume5.pdf",
        jobPostingName: "Backend Engineer",
        jobPostingId: "job-2",
      },
      {
        id: 6,
        name: "Lisa Garcia",
        email: "lisa.garcia@email.com",
        phone: "+1234567895",
        status: "Interview",
        score: 91,
        createdAt: "2024-01-10T13:20:00Z",
        resumeFile: "https://example.com/resume6.pdf",
        jobPostingName: "Full Stack Developer",
        jobPostingId: "job-4",
      },
      {
        id: 7,
        name: "Tom Anderson",
        email: "tom.anderson@email.com",
        phone: "+1234567896",
        status: "In-Review",
        score: 82,
        createdAt: "2024-01-09T08:45:00Z",
        resumeFile: "https://example.com/resume7.pdf",
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 8,
        name: "Emma Davis",
        email: "emma.davis@email.com",
        phone: "+1234567897",
        status: "Hired",
        score: 95,
        createdAt: "2024-01-08T15:10:00Z",
        resumeFile: "https://example.com/resume8.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 3,
        name: "Mike Johnson",
        email: "mike.johnson@email.com",
        phone: "+1234567892",
        status: "Hired",
        score: 88,
        createdAt: "2024-01-13T09:15:00Z",
        resumeFile: "https://example.com/resume3.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
      {
        id: 4,
        name: "Sarah Wilson",
        email: "sarah.wilson@email.com",
        phone: "+1234567893",
        status: "Rejected",
        score: 65,
        createdAt: "2024-01-12T16:45:00Z",
        resumeFile: null,
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 5,
        name: "David Brown",
        email: "david.brown@email.com",
        phone: "+1234567894",
        status: "In-Review",
        score: 78,
        createdAt: "2024-01-11T11:30:00Z",
        resumeFile: "https://example.com/resume5.pdf",
        jobPostingName: "Backend Engineer",
        jobPostingId: "job-2",
      },
      {
        id: 6,
        name: "Lisa Garcia",
        email: "lisa.garcia@email.com",
        phone: "+1234567895",
        status: "Interview",
        score: 91,
        createdAt: "2024-01-10T13:20:00Z",
        resumeFile: "https://example.com/resume6.pdf",
        jobPostingName: "Full Stack Developer",
        jobPostingId: "job-4",
      },
      {
        id: 7,
        name: "Tom Anderson",
        email: "tom.anderson@email.com",
        phone: "+1234567896",
        status: "In-Review",
        score: 82,
        createdAt: "2024-01-09T08:45:00Z",
        resumeFile: "https://example.com/resume7.pdf",
        jobPostingName: "UI/UX Designer",
        jobPostingId: "job-3",
      },
      {
        id: 8,
        name: "Emma Davis",
        email: "emma.davis@email.com",
        phone: "+1234567897",
        status: "Hired",
        score: 95,
        createdAt: "2024-01-08T15:10:00Z",
        resumeFile: "https://example.com/resume8.pdf",
        jobPostingName: "Senior Frontend Developer",
        jobPostingId: "job-1",
      },
    ]
  },

  // Bulk update status for candidates
  bulkUpdateStatus: async (candidateIds, { status, currentStatuses }) => {
    await new Promise((resolve) => setTimeout(resolve, 800))

    console.log("Bulk updating candidates:", candidateIds, "to status:", status)
    return {
      success: true,
      updatedCount: candidateIds.length,
      message: `Successfully updated ${candidateIds.length} candidates to ${status}`,
    }
  },
}
